language: php
php:
  - 7.0

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true

cache:
  directories:
    - $HOME/.composer/cache/files

before_script:
  - composer self-update
  - composer require --dev php-coveralls/php-coveralls
  - composer install --dev

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./travis/run_on_pull_requests; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./travis/run_on_non_pull_requests; fi'

after_script:
  - vendor/bin/php-coveralls -v